// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['api']['AgentService']['ClearHistory']();
}

export function GetHistory() {
  return window['go']['api']['AgentService']['GetHistory']();
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['api']['AgentService']['SendMessage'](arg1, arg2, arg3, arg4);
}

export function SetContext(arg1) {
  return window['go']['api']['AgentService']['SetContext'](arg1);
}

export function StopGeneration() {
  return window['go']['api']['AgentService']['StopGeneration']();
}
