// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {conversations} from '../models';
import {context} from '../models';

export function ClearHistory():Promise<void>;

export function GetHistory():Promise<Array<conversations.Message>>;

export function SendMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StopGeneration():Promise<void>;
