// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEntry(arg1, arg2, arg3) {
  return window['go']['api']['DNSService']['CreateEntry'](arg1, arg2, arg3);
}

export function DeleteEntry(arg1) {
  return window['go']['api']['DNSService']['DeleteEntry'](arg1);
}

export function ListEntries(arg1) {
  return window['go']['api']['DNSService']['ListEntries'](arg1);
}

export function SetContext(arg1) {
  return window['go']['api']['DNSService']['SetContext'](arg1);
}
