// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function CreateEntry(arg1:string,arg2:string,arg3:string):Promise<models.DNSEntry>;

export function DeleteEntry(arg1:string):Promise<void>;

export function ListEntries(arg1:string):Promise<Array<models.DNSEntry>>;

export function SetContext(arg1:context.Context):Promise<void>;
