// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDNSLogs(arg1) {
  return window['go']['api']['LogsService']['GetDNSLogs'](arg1);
}

export function GetLogs(arg1) {
  return window['go']['api']['LogsService']['GetLogs'](arg1);
}

export function GetLogsSince(arg1) {
  return window['go']['api']['LogsService']['GetLogsSince'](arg1);
}

export function SetContext(arg1) {
  return window['go']['api']['LogsService']['SetContext'](arg1);
}
