// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetDNSLogs(arg1:number):Promise<Array<Record<string, any>>>;

export function GetLogs(arg1:number):Promise<Array<Record<string, any>>>;

export function GetLogsSince(arg1:number):Promise<Array<Record<string, any>>>;

export function SetContext(arg1:context.Context):Promise<void>;
