// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetCurrent():Promise<Record<string, any>>;

export function GetHistory(arg1:string):Promise<Record<string, any>>;

export function SetContext(arg1:context.Context):Promise<void>;
