// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrent() {
  return window['go']['api']['MetricsService']['GetCurrent']();
}

export function GetHistory(arg1) {
  return window['go']['api']['MetricsService']['GetHistory'](arg1);
}

export function SetContext(arg1) {
  return window['go']['api']['MetricsService']['SetContext'](arg1);
}
