// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function Create(arg1:models.CreateRouteRequest):Promise<models.Route>;

export function Delete(arg1:string):Promise<void>;

export function Get(arg1:string):Promise<models.Route>;

export function List():Promise<Array<models.Route>>;

export function ListTemplates():Promise<Array<models.Template>>;

export function Preview(arg1:models.CreateRouteRequest):Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Update(arg1:string,arg2:models.CreateRouteRequest):Promise<models.Route>;
