// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['api']['RouteService']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['api']['RouteService']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['api']['RouteService']['Get'](arg1);
}

export function List() {
  return window['go']['api']['RouteService']['List']();
}

export function ListTemplates() {
  return window['go']['api']['RouteService']['ListTemplates']();
}

export function Preview(arg1) {
  return window['go']['api']['RouteService']['Preview'](arg1);
}

export function SetContext(arg1) {
  return window['go']['api']['RouteService']['SetContext'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['api']['RouteService']['Update'](arg1, arg2);
}
