// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAll() {
  return window['go']['api']['SettingsService']['GetAll']();
}

export function Set(arg1, arg2) {
  return window['go']['api']['SettingsService']['Set'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['api']['SettingsService']['SetContext'](arg1);
}
