// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStatus() {
  return window['go']['api']['StatusService']['GetStatus']();
}

export function IsDaemonRunning() {
  return window['go']['api']['StatusService']['IsDaemonRunning']();
}

export function SetContext(arg1) {
  return window['go']['api']['StatusService']['SetContext'](arg1);
}

export function GetDNSStatus() {
  return window['go']['api']['StatusService']['GetDNSStatus']();
}
