// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function GetCertInfo():Promise<Record<string, any>>;

export function GetDNSStatus():Promise<Array<Record<string, any>>>;

export function GetStatus():Promise<models.DaemonStatus>;

export function IsDaemonRunning():Promise<boolean>;

export function SetContext(arg1:context.Context):Promise<void>;
