// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function Create(arg1:string):Promise<models.ManagedTLD>;

export function Delete(arg1:string):Promise<void>;

export function List():Promise<Array<models.ManagedTLD>>;

export function SetContext(arg1:context.Context):Promise<void>;
